"""add_transcript_field

Revision ID: 3627df3c65a6
Revises: 5e5aee345429
Create Date: 2025-01-12 20:11:46.314121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3627df3c65a6'
down_revision = '5e5aee345429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcript', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.drop_column('transcript')

    # ### end Alembic commands ###
