"""Add emotion analysis fields

Revision ID: 5e5aee345429
Revises: d04ac4af7650
Create Date: 2025-01-12 18:42:21.349431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e5aee345429'
down_revision = 'd04ac4af7650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotion_scores', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dominant_emotion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tone_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('confidence_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.drop_column('confidence_score')
        batch_op.drop_column('tone_analysis')
        batch_op.drop_column('dominant_emotion')
        batch_op.drop_column('emotion_scores')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('google_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('google_id', name='user_google_id_key')
    )
    # ### end Alembic commands ###
