"""Add summary field

Revision ID: add_summary_field
Revises: 5e5aee345429
Create Date: 2025-01-12 19:15:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_summary_field'
down_revision = '5e5aee345429'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_analyses', schema=None) as batch_op:
        batch_op.drop_column('summary')
    # ### end Alembic commands ###
