"""Initial migration

Revision ID: d04ac4af7650
Revises: 
Create Date: 2025-01-08 18:55:17.264763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd04ac4af7650'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('has_narration', sa.Boolean(), nullable=True),
    sa.Column('has_underscore', sa.Boolean(), nullable=True),
    sa.Column('has_sound_effects', sa.Boolean(), nullable=True),
    sa.Column('songs_count', sa.Integer(), nullable=True),
    sa.Column('environments', sa.Text(), nullable=True),
    sa.Column('characters_mentioned', sa.Text(), nullable=True),
    sa.Column('speaking_characters', sa.Text(), nullable=True),
    sa.Column('themes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_analyses')
    # ### end Alembic commands ###
